name: Push + Check Scan

on: 
  workflow_dispatch:
    inputs:
      ecr-registry-id:
        required: false
      ecr-repo:
        required: true
      aws-region:
        required: true
      iam-role:
        required: true
      tag:
        required: true
      fail-on:
        type: choice
        description: Severity to cause failure
        options: 
          - CRITICAL
          - HIGH
          - MEDIM
          - LOW
          - INFORMATIONAL
          - UNDEFINED
          - BANANA
      ignore:
        required: false
      timeout:
        default: '60'
      consistency-delay:
        default: '15'
      
jobs:
  test-check-aws-inspector-action:
    runs-on: ubuntu-latest
    name: Test check-aws-inspector
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: Dockerfile
          sparse-checkout-cone-mode: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{github.event.inputs.iam-role}}
          aws-region: ${{github.event.inputs.aws-region}}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{github.event.inputs.ecr-registry-id || steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: ${{github.event.inputs.ecr-repo}}
          IMAGE_TAG: ${{github.event.inputs.tag}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Check results of aws inspect on image
        id: check-aws-inspector
        uses: ecperth/check-aws-inspector@v1.1
        with:
          repository: ${{github.event.inputs.ecr-repo}}
          registryId: ${{github.event.inputs.tag}}
          tag: ${{github.event.inputs.tag}}
          fail-on: ${{github.event.inputs.fail-on}}
          ignore: ${{github.event.inputs.ignore}}
          timeout: ${{github.event.inputs.timeout}}
          consistency-delay: ${{github.event.inputs.consistency-delay}}

      - name: Print the findings
        if: always()
        run: echo "${{steps.check-aws-inspector.outputs.findingSeverityCounts}}"
