name: Push + Check Scan

env:
  AWS_ACCOUNT_ID: ${{vars.AWS_ACCOUNT_ID}}
  AWS_REGION: ${{vars.AWS_REGION}}

on: 
  workflow_dispatch:
    inputs:
      base-image:
        required: true
        default: amazonlinux:2023
      image-tag:
        required: false
      image-digest:
        required: false
      fail-on:
        type: choice
        description: Severity to cause failure
        options: 
          - CRITICAL
          - HIGH
          - MEDIM
          - LOW
          - INFORMATIONAL
          - UNDEFINED
          - BANANA
      ignore:
        required: false
      timeout:
        default: '60'
      consistency-delay:
        default: '15'
      
jobs:
  test-check-aws-inspector-action:
    runs-on: ubuntu-latest
    name: Test check-aws-inspector
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: docker/Dockerfile
          sparse-checkout-cone-mode: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/github-iam-role
          aws-region: ${{env.AWS_REGION}}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, tag, and push image to Amazon ECR
        id: build
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: check-aws-inspector-test
          IMAGE_TAG: ${{github.event.inputs.image-tag}}
        run: |
          docker build -f docker/Dockerfile \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --build-arg BASE_IMAGE=${{github.event.inputs.base-image}} \
          --build-arg TAG=${{github.event.inputs.image-tag}} \
          .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo digest=$(docker images --no-trunc --quiet $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG) >> $GITHUB_OUTPUT

      - name: Check results of aws inspect on image
        id: check-aws-inspector
        uses: ecperth/check-aws-inspector@v3
        with:
          repository: check-aws-inspector-test
          image-digest: ${{steps.build.outputs.digest}}
          fail-on: ${{github.event.inputs.fail-on}}
          ignore: ${{github.event.inputs.ignore}}
          timeout: ${{github.event.inputs.timeout}}
          consistency-delay: ${{github.event.inputs.consistency-delay}}

      - name: Print the findings
        if: always()
        run: echo "${{steps.check-aws-inspector.outputs.findingSeverityCounts}}"
